package blueprint

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Blueprint represents a captured Kubernetes cluster state
type Blueprint struct {
	// Metadata contains information about the blueprint itself
	Metadata BlueprintMetadata `json:"metadata"`
	
	// Resources contains all discovered Kubernetes resources
	Resources []Resource `json:"resources"`
}

// BlueprintMetadata contains metadata about the blueprint
type BlueprintMetadata struct {
	// Timestamp when the blueprint was generated
	Timestamp metav1.Time `json:"timestamp"`
	
	// Cluster information
	ClusterName string `json:"clusterName"`
	K8SVersion  string `json:"k8sVersion"`
	NodeCount   int    `json:"nodeCount"`
	
	// Generated by information
	GeneratedBy string `json:"generatedBy"`
}

// Resource represents a single Kubernetes resource
type Resource struct {
	// API version of the resource
	APIVersion string `json:"apiVersion"`
	
	// Kind of the resource
	Kind string `json:"kind"`
	
	// Metadata of the resource
	Metadata ResourceMetadata `json:"metadata"`
	
	// Spec of the resource (if applicable)
	Spec map[string]interface{} `json:"spec,omitempty"`
	
	// Status of the resource (if applicable)
	Status map[string]interface{} `json:"status,omitempty"`
}

// ResourceMetadata contains metadata for a resource
type ResourceMetadata struct {
	Name      string            `json:"name"`
	Namespace string            `json:"namespace,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}